@file:OptIn(ExperimentalTime::class)

package ru.izhxx.aichallenge.features.productassistant.impl.domain.usecase

import kotlinx.datetime.Instant
import ru.izhxx.aichallenge.features.productassistant.impl.domain.model.SupportTicket
import ru.izhxx.aichallenge.features.productassistant.impl.domain.model.TicketStatus
import ru.izhxx.aichallenge.features.productassistant.impl.domain.repository.ProductAssistantRepository
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

/**
 * Implementation of CreateTicketUseCase
 */
internal class CreateTicketUseCaseImpl(
    private val repository: ProductAssistantRepository
) : CreateTicketUseCase {
    
    override suspend fun invoke(
        title: String,
        description: String,
        tags: List<String>
    ): Result<SupportTicket> {
        return try {
            val newTicket = SupportTicket(
                id = "", // Will be generated by the MCP tool
                userId = "UserId",
                title = title,
                description = description,
                status = TicketStatus.OPEN,
                createdAt = getCurrentTimestamp(),
                updatedAt = getCurrentTimestamp(),
                tags = tags
            )
            
            repository.createTicket(newTicket)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    private fun getCurrentTimestamp(): Instant = Clock.System.now()
}
